# pull dogfish survey data

# Note
# SURVEY_SERIES_ID == 48) #comp work 2004, 2019, 2022, 2023
# SURVEY_SERIES_ID == 93) #circle hook dog surveys 2005 onwards (2005, 2008, 2011, 2014, 2019)
# SURVEY_SERIES_ID == 76) #all jhook and circle hook dog surveys 1986 onwards does not include 2004 (1986, 1989, 2005, 2008, 2011, 2014, 2019)
# SURVEY_SERIES_ID == 92) #j hook dog surveys 1986, 1989 only

# yelloweye rockfish were not sampled in earlier years. 1986/1989 maybe not 2004?
# 2004 comparison work had two gear types per set
# 2019 comparison work dropped separate lines per gear type
# 2022 comparison work has two gear types per set
# 2023 comparison work has two gear types per set  and was completed during the HBLL and DOG survey

library(tidyverse)
library(sf)
library(ggplot2)
library(here)
library(sp)
library(gfdata)
#remotes::install_github("pbs-assess/gfdata", ref = "trials", force = TRUE)

# pull inside sets data ------------------------------------------------
#survey ids include all of the dogfish surveys on the inside
d <- get_all_survey_sets("north pacific spiny dogfish", ssid = c(76, 48, 39, 40))
unique(d$survey_abbrev)
saveRDS(d, "data/raw/dogfish_sets_getall.rds")
dim(filter(d, fishing_event_id == 5883186)) #duplicate?? should be 2 not 4

hbllgfdata <- get_survey_sets(species = "north pacific spiny dogfish", ssid = c(76, 48, 39, 40))
saveRDS(hbllgfdata, "data/raw/dogfish_sets_gfdata.rds")

#pull inside samples data
#d <- get_all_survey_samples("north pacific spiny dogfish", ssid = c(76, 48, 39, 40))
d <- get_all_survey_samples("north pacific spiny dogfish", ssid = c(76, 48, 39, 40), include_event_info = TRUE)
unique(d$survey_abbrev)
saveRDS(d, "data-raw/dogfish_samples_getall.rds")

d <- get_survey_samples("north pacific spiny dogfish", ssid = c(76, 48, 39, 40))
unique(d$survey_abbrev)
length(unique(d$fishing_event_id))
saveRDS(d, "data-raw/dogfish_samples_gfdata.rds")



# # pull all species for each survey - dont need ----------------------------------------
# catch_dogfish <- gfdata::run_sql("GFBioSQL", "SELECT
# FEC.FISHING_EVENT_ID,
# FE.FE_PARENT_EVENT_ID,
# FE.FE_SUB_LEVEL_ID,
# C.SPECIES_CODE,
# SP.SPECIES_COMMON_NAME,
# SP.SPECIES_SCIENCE_NAME,
# SUM(CATCH_COUNT) CATCH_COUNT
# FROM FISHING_EVENT_CATCH FEC
# INNER JOIN FISHING_EVENT FE ON FE.FISHING_EVENT_ID = FEC.FISHING_EVENT_ID
# INNER JOIN CATCH C ON C.CATCH_ID = FEC.CATCH_ID
# INNER JOIN TRIP_SURVEY TS ON TS.TRIP_ID = FEC.TRIP_ID
# INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
# INNER JOIN GFBioSQL.dbo.SPECIES SP ON SP.SPECIES_CODE = C.SPECIES_CODE
# WHERE SURVEY_SERIES_ID IN (48, 92, 93)
# GROUP BY FEC.TRIP_ID,
# FEC.FISHING_EVENT_ID,
# FE.FE_PARENT_EVENT_ID,
# FE.FE_SUB_LEVEL_ID,
# C.SPECIES_CODE,
# SP.SPECIES_COMMON_NAME,
# SP.SPECIES_SCIENCE_NAME
# ORDER BY FEC.FISHING_EVENT_ID")
# saveRDS(catch_dogfish, "data-raw/dogfish_allspeciescatch.rds")
# 
# 
# catch_hbll <- gfdata::run_sql("GFBioSQL", "SELECT
# FEC.FISHING_EVENT_ID,
# FE.FE_PARENT_EVENT_ID,
# FE.FE_SUB_LEVEL_ID,
# C.SPECIES_CODE,
# SP.SPECIES_COMMON_NAME,
# SP.SPECIES_SCIENCE_NAME,
# SUM(CATCH_COUNT) CATCH_COUNT
# FROM FISHING_EVENT_CATCH FEC
# INNER JOIN FISHING_EVENT FE ON FE.FISHING_EVENT_ID = FEC.FISHING_EVENT_ID
# INNER JOIN CATCH C ON C.CATCH_ID = FEC.CATCH_ID
# INNER JOIN TRIP_SURVEY TS ON TS.TRIP_ID = FEC.TRIP_ID
# INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
# INNER JOIN GFBioSQL.dbo.SPECIES SP ON SP.SPECIES_CODE = C.SPECIES_CODE
# WHERE SURVEY_SERIES_ID IN (39, 40)
# GROUP BY FEC.TRIP_ID,
# FEC.FISHING_EVENT_ID,
# FE.FE_PARENT_EVENT_ID,
# FE.FE_SUB_LEVEL_ID,
# C.SPECIES_CODE,
# SP.SPECIES_COMMON_NAME,
# SP.SPECIES_SCIENCE_NAME
# ORDER BY FEC.FISHING_EVENT_ID")
# saveRDS(catch_hbll, "data-raw/hbll_allspeciescatch.rds")
# 
# info <- gfdata::run_sql("GFBioSQL", "SELECT
# S.SURVEY_SERIES_ID,
# SURVEY_SERIES_DESC,
# FE.FE_MISC_COMMENT,
# FE.FE_FISHING_GROUND_COMMENT,
# S.SURVEY_ID, SURVEY_DESC, FE.FE_MAJOR_LEVEL_ID, SK.FE_SUB_LEVEL_ID,
# SK.HOOK_DESC, SK.HOOKSIZE_DESC,
# YEAR(TR.TRIP_START_DATE) AS YEAR,
# FE.FISHING_EVENT_ID,
# FE.FE_PARENT_EVENT_ID,
# LGLSP_HOOK_COUNT,
# FE_START_LATTITUDE_DEGREE + FE_START_LATTITUDE_MINUTE / 60 AS LATITUDE,
# -(FE_START_LONGITUDE_DEGREE + FE_START_LONGITUDE_MINUTE / 60) AS LONGITUDE,
# FE_END_DEPLOYMENT_TIME, FE_BEGIN_RETRIEVAL_TIME, FE.GROUPING_CODE, GROUPING_DESC, GROUPING_SPATIAL_ID, GROUPING_DEPTH_ID,
# TR.TRIP_START_DATE,
# TR.TRIP_END_DATE,
# FE_BEGINNING_BOTTOM_DEPTH AS DEPTH_M,
# FE.TRIP_ID
# FROM FISHING_EVENT FE
# LEFT JOIN (
#   SELECT TRIP_ID, FE.FISHING_EVENT_ID, LLSP.LGLSP_HOOK_COUNT, FE_MAJOR_LEVEL_ID, FE_SUB_LEVEL_ID, H.HOOK_DESC, HSZ.HOOKSIZE_DESC
#   FROM FISHING_EVENT FE
#   INNER JOIN LONGLINE_SPECS LLSP ON LLSP.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
#   LEFT JOIN HOOK H ON H.HOOK_CODE = LLSP.HOOK_CODE
#   LEFT JOIN HOOKSIZE HSZ ON HSZ.HOOKSIZE_CODE = LLSP.HOOKSIZE_CODE
# ) SK ON SK.TRIP_ID = FE.TRIP_ID AND SK.FE_MAJOR_LEVEL_ID = FE.FE_MAJOR_LEVEL_ID
# INNER JOIN TRIP_SURVEY TS ON FE.TRIP_ID = TS.TRIP_ID
# INNER JOIN TRIP TR ON FE.TRIP_ID = TR.TRIP_ID
# INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
# INNER JOIN SURVEY_SERIES SS ON SS.SURVEY_SERIES_ID = S.SURVEY_SERIES_ID
# LEFT JOIN GROUPING G ON G.GROUPING_CODE = FE.GROUPING_CODE
# WHERE S.SURVEY_SERIES_ID IN (39, 40)
# AND FE.FE_MAJOR_LEVEL_ID < 1000 AND FE_PARENT_EVENT_ID IS NULL
# ORDER BY YEAR, TRIP_ID, FE_MAJOR_LEVEL_ID,  FE_SUB_LEVEL_ID")
# saveRDS(info, "data-raw/hbll_sets.rds")
# 
# info <- gfdata::run_sql("GFBioSQL", "SELECT
# S.SURVEY_SERIES_ID,
# SURVEY_SERIES_DESC, FE.FE_MISC_COMMENT, FE.FE_FISHING_GROUND_COMMENT,
# S.SURVEY_ID, SURVEY_DESC, FE.FE_MAJOR_LEVEL_ID, SK.FE_SUB_LEVEL_ID,
# SK.HOOK_DESC, SK.HOOKSIZE_DESC,
# YEAR(TR.TRIP_START_DATE) AS YEAR,
# FE.FISHING_EVENT_ID,
# FE.FE_PARENT_EVENT_ID,
# LGLSP_HOOK_COUNT,
# FE_START_LATTITUDE_DEGREE + FE_START_LATTITUDE_MINUTE / 60 AS LATITUDE,
# -(FE_START_LONGITUDE_DEGREE + FE_START_LONGITUDE_MINUTE / 60) AS LONGITUDE,
# FE_END_DEPLOYMENT_TIME, FE_BEGIN_RETRIEVAL_TIME, FE.GROUPING_CODE, GROUPING_DESC, GROUPING_SPATIAL_ID, GROUPING_DEPTH_ID,
# TR.TRIP_START_DATE,
# TR.TRIP_END_DATE,
# FE_BEGINNING_BOTTOM_DEPTH AS DEPTH_M,
# FE.TRIP_ID
# FROM FISHING_EVENT FE
# LEFT JOIN (
#   SELECT TRIP_ID, FE.FISHING_EVENT_ID, LLSP.LGLSP_HOOK_COUNT, FE_MAJOR_LEVEL_ID, FE_SUB_LEVEL_ID, H.HOOK_DESC, HSZ.HOOKSIZE_DESC
#   FROM FISHING_EVENT FE
#   INNER JOIN LONGLINE_SPECS LLSP ON LLSP.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
#   LEFT JOIN HOOK H ON H.HOOK_CODE = LLSP.HOOK_CODE
#   LEFT JOIN HOOKSIZE HSZ ON HSZ.HOOKSIZE_CODE = LLSP.HOOKSIZE_CODE
# ) SK ON SK.TRIP_ID = FE.TRIP_ID AND SK.FE_MAJOR_LEVEL_ID = FE.FE_MAJOR_LEVEL_ID
# INNER JOIN TRIP_SURVEY TS ON FE.TRIP_ID = TS.TRIP_ID
# INNER JOIN TRIP TR ON FE.TRIP_ID = TR.TRIP_ID
# INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
# INNER JOIN SURVEY_SERIES SS ON SS.SURVEY_SERIES_ID = S.SURVEY_SERIES_ID
# LEFT JOIN GROUPING G ON G.GROUPING_CODE = FE.GROUPING_CODE
# WHERE S.SURVEY_SERIES_ID IN (48, 92, 93)
# AND FE.FE_MAJOR_LEVEL_ID < 1000 AND FE_PARENT_EVENT_ID IS NULL
# ORDER BY YEAR, TRIP_ID, FE_MAJOR_LEVEL_ID,  FE_SUB_LEVEL_ID")
# saveRDS(info, "data-raw/dogfish_sets.rds")